export enum People {
  AliciaS = 'Alicia S',
  AmandaS = 'Amanda S',
  ChrisS = 'Chris S',
  KenS = 'Ken S',
  ThomasS = 'Thomas S',
  TomS = 'Tom S',
  JackI = 'Jack i',
  TeddyI = 'Teddy i',
  ZachH = 'Zach H',
  ZakA = 'Zak Ben A',
  LoganR = 'Logan R',
  NathanW = 'Nathan W',
  ElizabethS = 'Elizabeth S',
  MeganW = 'Megan W',
  FrScott = 'Father Scott',
  JoeS = 'Joe S',
  // ... Add more people as needed
  Unknown = 'n/a',
}
